### ISSUE TITLE
Radar and paper 

### ISSUE THREAD

**Issue by TT22TY** [SantiMontiel/LiDAR-Radar-MOT#1]
Hello,

Thanks for your sharing!

I was wondering that where do you use radar? Besides, could you please share your paper "Multi-Object Tracking system based on LiDAR and Radar for Intelligent Vehicles Applications"  as well ?

Thank you!

**Comment by SantiMontiel** [comment]
Hello,

The content that is uploaded right now is an early development version. Radar will be implemented in future stages and paper is not released yet.

Thank you!

**Comment by TT22TY** [comment]
> Hello,
> 
> The content that is uploaded right now is an early development version. Radar will be implemented in future stages and paper is not released yet.
> 
> Thank you!

Thank you so much!
